global:
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files:
 - rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - 192.168.43.218:9093
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - localhost:9090
 - job_name: node
   static_configs:
    - targets:
       - 192.168.43.218:9100 # because it is in another container on the same host, it cannot be accessed with localhost, instead the inet ip works 
